import './globals.css'
import Navbar from '@/components/Navbar'
import Footor from '@/components/Footor'

export const metadata = {
  title: 'Flexibless',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>
        {children}
        </main>
        <Footor/>
        </body>
    </html>
  )
}
